services:
  api:
    build:
      context: ./backend/Scoreboard.Api
      dockerfile: Dockerfile
    container_name: scoreboard-api
    networks:
      - scoreboard-net
    environment:
      ASPNETCORE_URLS: "http://+:5071"
      ConnectionStrings__Sql: "Server=sqlserver_main,1433;Database=ScoreboardDB;User Id=sa;Password=Anevictor1712@;TrustServerCertificate=True;"
    ports:
      - "5071:5071"

  frontend:
    build:
      context: ./frontend/scoreboard
      dockerfile: Dockerfile
    container_name: scoreboard-frontend
    networks:
      - scoreboard-net
    ports:
      - "80:80"

networks:
  scoreboard-net:
    external: true
