version: "3.9"

services:
  marcador-api:
    build: ./backend
    container_name: marcador-api
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver_main,1433;Database=ScoreboardDB;User ID=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
    depends_on:
      - sqlserver_main
    networks:
      - infraestructura_network

  marcador-frontend:
    build: ./frontend
    container_name: marcador-frontend
    restart: always
    depends_on:
      - marcador-api
    networks:
      - infraestructura_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - marcador-api
      - marcador-frontend
    networks:
      - infraestructura_network

networks:
  infraestructura_network:
    driver: bridge
